#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "xuelian",
                "name":        "天山雪蓮",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/xuelian.c",
        ]),
        ([
                "id":          "piqiu",
                "name":        "皮裘",
                "type":        "尋",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/piqiu.c",
        ]),
        ([
                "id":          "zi pao",
                "name":        "紫袍",
                "type":        "尋",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/foshan/npc/obj/magcloth.c",
        ]),
        ([
                "id":          "red cloth",
                "name":        "[1;31m紅綾襖[2;37;0m",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/red_cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/fuzhou/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/emei/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/hangzhou/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "繡梅青衣",
                "type":        "尋",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/meizhuang/npc/obj/qingyi.c",
        ]),
        ([
                "id":          "futou",
                "name":        "大斧頭",
                "type":        "尋",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/futou.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/quanzhou/npc/obj/cloth.c",
        ]),
        ([
                "id":          "tonggu",
                "name":        "銅鼓",
                "type":        "尋",
                "bonus":       80,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/tonggu.c",
        ]),
        ([
                "id":          "pao",
                "name":        "灰色道袍",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/wudang/obj/greyrobe.c",
        ]),
        ([
                "id":          "scarf",
                "name":        "[1;33m繡花小方巾[2;37;0m",
                "type":        "尋",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/xiu-scarf.c",
        ]),
        ([
                "id":          "moon-dress",
                "name":        "[1;37m瓊花皎月裳[2;37;0m",
                "type":        "尋",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/moon-dress.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "[1;36m淺藍色馬褂[2;37;0m",
                "type":        "尋",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/cloth.c",
        ]),
        ([
                "id":          "tonghao",
                "name":        "銅號",
                "type":        "尋",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/tonghao.c",
        ]),
        ([
                "id":          "tongbo",
                "name":        "銅鈸",
                "type":        "尋",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/tongbo.c",
        ]),
        ([
                "id":          "dongbula",
                "name":        "冬不拉",
                "type":        "尋",
                "bonus":       65,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/dongbula.c",
        ]),
        ([
                "id":          "mini-ao",
                "name":        "[34m綵緞緊身襖[2;37;0m",
                "type":        "尋",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/mini-dress.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       65,
                "msg1":        "",
                "object":      "/d/village/npc/obj/cloth.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "白布黑邊袈裟",
                "type":        "尋",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/shaolin/obj/qing-cloth.c",
        ]),
        ([
                "id":          "yao qin",
                "name":        "瑤琴",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/yaoqin.c",
        ]),
        ([
                "id":          "white cloth",
                "name":        "白綢衫",
                "type":        "尋",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/whitecloth1.c",
        ]),
        ([
                "id":          "da hui",
                "name":        "烏夷大麾",
                "type":        "尋",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/wdahui.c",
        ]),
        ([
                "id":          "tong qun",
                "name":        "筒裙",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/tongqun.c",
        ]),
        ([
                "id":          "duan qun",
                "name":        "台夷短裙",
                "type":        "尋",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/tduanqun.c",
        ]),
        ([
                "id":          "mao tan",
                "name":        "毛毯",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/maotan.c",
        ]),
        ([
                "id":          "ken ao",
                "name":        "窄裉襖",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/kenao.c",
        ]),
        ([
                "id":          "kan dao",
                "name":        "砍刀",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/kandao.c",
        ]),
        ([
                "id":          "pao",
                "name":        "青色道袍",
                "type":        "尋",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/cynrobe.c",
        ]),
        ([
                "id":          "duan qun",
                "name":        "擺夷短裙",
                "type":        "尋",
                "bonus":       65,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/bduanqun.c",
        ]),
        ([
                "id":          "yao fen",
                "name":        "藥粉",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/city/obj/yaofen.c",
        ]),
        ([
                "id":          "golden necklace",
                "name":        "金項鍊",
                "type":        "尋",
                "bonus":       57,
                "msg1":        "",
                "object":      "/d/city/obj/necklace.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/city/obj/cloth.c",
        ]),
        ([
                "id":          "blade",
                "name":        "鋼刀",
                "type":        "尋",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/city/npc/obj/gangdao.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/city/npc/obj/cloth.c",
        ]),
        ([
                "id":          "linen",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/linen.c",
        ]),
        ([
                "id":          "tu rou",
                "name":        "兔肉",
                "type":        "尋",
                "bonus":       80,
                "msg1":        "",
                "object":      "/d/baituo/obj/turou.c",
        ]),
        ([
                "id":          "chai dao",
                "name":        "柴刀",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/baituo/obj/chaidao.c",
        ]),
        ([
                "id":          "mu chai",
                "name":        "木柴",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/baituo/obj/chai.c",
        ]),
        ([
                "id":          "cao mei",
                "name":        "草莓",
                "type":        "尋",
                "bonus":       80,
                "msg1":        "",
                "object":      "/d/baituo/obj/caomei.c",
        ]),
});

mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
