#include <ansi.h>

mapping all_type = ([
        "weapon" : ({ "blade", "club", "hammer", "sword", "staff", "whip", "throwing", "xsword", }),
        "armor"  : ({ "armor", "boots", "cloth", "hands", "finger", "head", "waist", "wrists", "surcoat", }),
        "rings"  : ({ "rings", "neck", "charm", }),
        "gem"    : ({ "gem", }),
]);

string *weapon_type = ({
        "blade", "hammer", "sword", "staff", "whip", "club", "throwing", "xsword",
}); 

string *armor_type = ({
        "armor", "boots", "cloth", "hands", "finger", "head", "waist", "wrists", "surcoat",
});

string *rings_type = ({
        "rings", "neck", "charm",
});

string *item_color = ({
          HIW,         HIB,         HIC,         HIR,         HIM,         HIY,         HIG,
          WHT,         BLU,         CYN,         RED,         MAG,         YEL,         NOR,
});

mapping type_list = ([
        "blade"                :        
                ([
                        "踢掖湮興絮"        :        "jinbei blade", 
                        "藷圮湮絮"        :        "menshan blade", 
                        "瘀陳栠絮"        :        "chaoyang blade",  
                        "砓掏嘉堎絮"        :        "guyue blade",  
                        "興刓絮"        :        "kanshan blade",  
                        "潑謗絮"        :        "sanjian blade",  
                        "磁圮啣藷絮"        :        "heshan blade", 
                        "踢掖興刓絮"        :        "kanshan blade",  
                        "栜酃絮"        :        "yanling blade",  
                        "肣絮"        :        "qingtong blade",  
                        "竣瘀絮"        :        "danfeng blade",  
                        "啣藷綻荍絮"        :        "hongying blade",  
                        "凄絮"        :        "xiurong blade",  
                        "陎腄豪絮"        :        "qixing blade",  
                        "誥挴絮"        :        "huya blade", 
                        "嬝嫉匐遠絮"        :        "bahuan blade",  
                        "赶邂豜踢絮"        :        "yulin blade",  
                        "脫寤芛絮"        :        "guitou blade",  
                        "謠窅絮"        :        "liangyin blade",  
                        "萇嫖絮"        :        "dianguang blade",  
                        "惘渠踢絮"        :        "cuojin blade",  
                        "喪肣絮"        :        "chitong blade",  
                        "衢阨絮"        :        "pishui blade",  
                        "詩絮"        :        "qinggang blade", 
                ]),

        "hammer"        :        
                ([
                        "匐濕豜踢晴"        :        "zijin hammer",   
                        "匐濕酴踢晴"        :        "huangjin hammer",    
                        "匐寑汜肣晴"        :        "shengtong hammer",    
                        "匐濕謠窅晴"        :        "liangyin hammer",    
                        "旛沺崏蚐晴"        :        "bingtie hammer",    
                        "匐寑謠窅晴"        :        "bagua hammer",    
                        "濯嘆怤踢晴"        :        "leigu hammer",    
                        "韓芛蟈赽晴"        :        "longtou hammer",   
                        "匐濕汜沺晴"        :        "baleng hammer",    
                        "匐寑旛沺晴"        :        "bagua hammer",    
                        "窪誥肣晴"        :        "heihu hammer",    
                        "拫踢晴"        :        "wujin hammer",    
                        "揤參擱韓晴"        :        "lanlong hammer",    
                        "醱喪肣晴"        :        "chitong hammer",    
                        "圖坲晴"        :        "guasuo hammer",    
                        "匐惘萇嫖晴"        :        "dianguang hammer",    
                        "肣蟈赽晴"        :        "lianzi hammer",    
                        "萇嫖豜踢晴"        :        "zijin hammer",    
                        "匐濩肣晴"        :        "baleng hammer",    
                        "骰埴晴"        :        "hunyuan hammer",    
                        "肣恮圖晴"        :        "wogua hammer",   
                        "赽譫唭栒晴"        :        "zimu hammer",    
                        "謠窅蟈赽晴"        :        "lianzi hammer",    
                        "匐褒豜踢晴"        :        "bajiao hammer",    
                        "綻肣晴"        :        "hongtong hammer",    
                        "匐惘謠窅晴"        :        "babao hammer",    
                ]),
        "sword"                :        
                ([
                        "侂恇嘉隅膛"        :        "guding sword",   
                        "陎黮箇膛"        :        "liuhong sword",    
                        "轄栭瑟膛"        :        "qingfeng sword",    
                        "芵韓膛"        :        "toulong sword",    
                        "犮藷惘膛"        :        "sanmeng sword",    
                        "豜萇邞膛"        :        "zidian sword",    
                        "豜邞膛"        :        "zishuang sword",    
                        "捺鍾膛"        :        "biling sword",    
                        "攫彴惘膛"        :        "panshe sword",    
                        "攫韓惘膛"        :        "panlong sword",    
                        "毞曖膛"        :        "tianlang sword",    
                        "拫像膛"        :        "wugou sword",    
                        "詩膛"        :        "qinggang sword",    
                        "唭栒膛"        :        "yanyang sword",    
                        "膛"        :        "qingping sword",    
                        "怮磁膛"        :        "taihe sword",    
                        "堎鳶韓膛"        :        "huolong sword",    
                        "韓膛"        :        "qinglong sword",    
                        "紻韓膛"        :        "zhulong sword",    
                        "嬪韓膛"        :        "kunlong sword",    
                        "漁嫖膛"        :        "hanguang sword",    
                        "霞珔膛"        :        "liuye sword",    
                        "煦毞膛"        :        "fentian sword",    
                        "邈珔瑟膛"        :        "luoye sword",   
                        "媼詩膛"        :        "qinggang sword",    
                        "酗箇膛"        :        "changhong sword",   
                        "梮珈膛"        :        "zhanxian sword",    
                        "拫韓膛"        :        "wulong sword",    
                        "堁膛"        :        "qingyun sword",    
                        "燧豪惘膛"        :        "lihua sword",    
                        "啞嫖膛"        :        "baiguang sword",    
                        "笛堁惘膛"        :        "caiyun sword",    
                ]),
        "staff"                :        
                ([
                        "秝栠桱"        :        "yinyang staff",   
                        "轏噘桱"        :        "lilai staff",  
                        "蘋褒桱"        :        "mojiao staff",  
                        "籟褒桱"        :        "niujiao staff",  
                        "黃韓桱"        :        "dulong staff",  
                        "陎拏赶桱"        :        "woyu staff",  
                        "旛沺間趼桱"        :        "dingzi staff",  
                        "旛沺輒惕桱"        :        "huaibao staff",  
                        "韓芛桱"        :        "longtou staff",  
                        "誥芛桱"        :        "hutou staff", 
                        "陎桱"        :        "qixing staff",  
                        "誘忒邧沺桱"        :        "hushou staff",  
                        "唭栒桱"        :        "yanyang staff",  
                        "等絮拏赶桱"        :        "woyu staff",  
                        "麥眅桱"        :        "chenxiang staff",  
                        "僑禮誥芛桱"        :        "goulou staff",  
                        "旛沺唭栒桱"        :        "yanyang staff", 
                ]),
        "club"                :        
                ([
                        "阨鳶韓堵"        :        "qiulong club",   
                        "羲刓堵"        :        "kaishan club", 
                        "隊隊曖挴堵"        :        "dingding club", 
                        "汆踢椲瑆堵"        :        "shenjin club", 
                        "豜踢繵韓堵"        :        "zijin club", 
                        "拫蚐堵"        :        "wuyou club", 
                        "匐濩堵"        :        "baleng club", 
                        "韓芛堵"        :        "longtou club", 
                        "骰沺堵"        :        "huntie club", 
                        "毞賹堵"        :        "tiangang club", 
                        "黃韓汆踢堵"        :        "dulong club", 
                        "俴氪堵"        :        "xingzhe club", 
                        "謠窅曖挴堵"        :        "langya club", 
                        "肣椲瑆堵"        :        "qingtong club", 
                        "旛沺蹟佪堵"        :        "luosi club", 
                        "踢佪枘彴堵"        :        "tengshe club", 
                        "踢嫖曖挴堵"        :        "jinguang club", 
                        "啃隊曖挴堵"        :        "baiding club", 
                        "豜枘堵"        :        "ziteng club", 
                        "肣堵曈"        :        "qingtong club", 
                        "踢佪堵曈"        :        "jinsi club",
                ]),
        "whip"                :        
                ([
                        "謠窅晝"        :        "liangyin whip",
                        "罣誹詩晝"        :        "zhujie whip",
                        "悸帣晝"        :        "baowei whip", 
                        "湖蔚晝"        :        "dajiang whip", 
                        "邯嘎秝瑞晝"        :        "tuogu whip", 
                        "踢韓晝"        :        "jinlong whip", 
                        "誥帣詩晝"        :        "huwei whip", 
                        "旛沺晝"        :        "bingtie whip", 
                        "韓芛瘀帣晝"        :        "longtou whip", 
                        "誥桉詩晝"        :        "huyan whip", 
                        "踢佪晝"        :        "jinsi whip", 
                        "綵竄晝"        :        "hulu whip", 
                        "實嘎晝"        :        "guigu whip", 
                        "赶帣晝"        :        "yugu whip", 
                        "彴嘎晝"        :        "shegu whip", 
                        "窅佪晝"        :        "yinsi whip", 
                        "殑堁禸韓晝"        :        "zheyun whip", 
                ]),

        "cloth"                :        
                ([
                        "鎊票畟"        :        "mabu cloth",
                        "蹬票畟"        :        "mianbu cloth",
                        "喙票畟"        :        "choubu cloth",
                        "滄悕畟"        :        "feixue cloth",
                        "珗藹畟"        :        "yemo cloth",
                        "佪畟"        :        "qingsi cloth",
                        "嬝毞蠱"        :        "jiutian cloth",
                        "剞拸蠱"        :        "xuwu cloth",
                        "琱蠱"        :        "qingming cloth",
                        "堁蹕畟"        :        "yunluo cloth",
                        "佪喙酗蠱"        :        "silk cloth",
                ]),
        "head"                :        
                ([
                        "齡韓晶芛"        :        "naolong kui",
                        "珗隴錳"        :        "yeming kui",
                        "瘀喔踢錳"        :        "fengchi kui",
                        "肣盡珔錳"        :        "heye kui",
                        "酴踢邟趼錳"        :        "huangjin kui", 
                        "窅褶錳"        :        "yinlian kui",
                        "煦阨錳"        :        "fenshui kui",
                        "拻瘀陳栠錳"        :        "chaoyang kui", 
                        "瘀喔堎隴錳"        :        "fengchi kui", 
                        "曖挴錳"        :        "langya kui", 
                        "拻瘀豪錳"        :        "wufeng kui", 
                        "怮呡錳"        :        "taisui kui", 
                        "郰毞錳"        :        "zuantian kui",
                        "謠窅誥芛錳"        :        "hutou kui", 
                        "悸赽錳"        :        "baozi kui", 
                        "維評踢錳"        :        "hudie kui", 
                        "邧瘀夢"        :        "shuangfeng guan", 
                        "踢瘀夢"        :        "jinfeng guan",  
                        "喪踢夢"        :        "chijin guan",  
                        "踢牳夢"        :        "jinxia guan", 
                        "豜踢夢"        :        "zijin guan",  
                        "旰楷踢夢"        :        "shufa guan",  
                        "嬝堁轄栭夢"        :        "lieyan guan", 
                ]),
        "neck"                :        
                ([
                        "窪緒勳蟈"        :        "heihu necklace",
                        "躓朸勳蟈"        :        "nvshen necklace",
                        "窅砐蟈"        :        "yin necklace",
                        "肣砐蟈"        :        "tong necklace",
                        "踢砐蟈"        :        "jin necklace",
                        "懦迶砐蟈"        :        "lanyu necklace",
                        "酴阨儒砐蟈"        :        "shuijing necklace",
                        "肣砐蟈"        :        "qingtong necklace",
                        "棣芛砐蟈"        :        "congtou necklace",
                        "鷐鷖砐蟈"        :        "kulou necklace",
                        "嘉攷砐蟈"        :        "gushu necklace",
                        "醵港砐蟈"        :        "feicui necklace",
                        "梨邂砐蟈"        :        "binglin necklace",
                ]),
        "armor"                :
                ([
                        "霞珔蹴罣霟"        :        "liuye armor",
                        "湮珔赶邂樅"        :        "yulin armor",
                        "湮珔韓邂樅"        :        "longlin armor",
                        "旛沺樅"        :        "bingtie armor", 
                        "喪踢霟樅"        :        "chijin armor", 
                        "酴踢樅"        :        "huangjin armor",
                        "實掖樅"        :        "guibei armor",
                        "蘋赶樅"        :        "moyu armor",
                        "喪肣湮珔樅"        :        "chitong armor",
                        "窅蚾樅"        :        "yinzhuang armor", 
                        "蟀遠旛沺霟"        :        "lianhuan armor",
                        "堎邈綻堁樅"        :        "yueluo armor",
                        "踢佪樅"        :        "jinsi armor",
                        "豜枘樅"        :        "ziteng armor",
                        "豜踢誘陑樅"        :        "huxin armor", 
                        "盡珔蟀遠樅"        :        "heye armor", 
                ]),
        "surcoat"        :        
                ([
                        "珗嫖蠹瑞"        :        "yeguang pifeng",
                        "酴踢蠹瑞"        :        "huangjin pifeng",
                        "蹴票須囑"        :        "mianbu pifeng",
                        "栺須囑"        :        "yangpi pifeng",
                        "喙剷須囑"        :        "chouduan pifeng",
                        "喪綻須囑"        :        "chihong pifeng",
                        "鍾褒蠹瑞"        :        "lingjiao pifeng",
                        "桵堎蠹瑞"        :        "zhanyue pifeng",
                        "祑忤蠹瑞"        :        "yishou pifeng",
                ]),
        "waist"                :        
                ([
                        "楞票殈湍"        :        "fanbu waist",
                        "淩殈湍"        :        "zhenpi waist",
                        "晤眽殈湍"        :        "bianzhi waist",
                        "棉票殈湍"        :        "cubu waist",
                        "汜沺殈湍"        :        "shengtie waist",
                        "踖賙殈湍"        :        "hupo waist",
                        "梨邂殈湍"        :        "binglin waist",
                        "啞窅殈湍"        :        "baiying waist",
                        "醵港殈湍"        :        "feicui waist",
                ]),
        "wrists"        :        
                ([
                        "棉票誘勂"        :        "cubu wrists",
                        "豜罣誘勂"        :        "zizhu wrists",
                        "嘉躂誘勂"        :        "gumu wrists",
                        "肣誘勂"        :        "qingtong wrists",
                        "儕沺誘勂"        :        "jingtie wrists",
                        "醵港誘勂"        :        "feicui wrists",
                        "酴踢誘勂"        :        "huangjin wrists",
                        "梨邂誘勂"        :        "bingling wrists",
                ]),
        "finger"        :
                ([
                        "蚗箝賭硌"        :        "yongheng ring",
                        "豪賭硌"        :        "hua ring",
                        "窅賭硌"        :        "yin ring",
                        "哏旆賭硌"        :        "weiyan ring",
                        "忑鍰賭硌"        :        "shouling ring",
                        "嘉攷賭硌"        :        "gushu ring",
                        "笐尪賭硌"        :        "yinshi ring",
                        "坋趼嘎賭"        :        "shizi ring",
                        "阨儒賭硌"        :        "shuijing ring",
                        "梨邂賭硌"        :        "bingling ring",
                        "醵港賭硌"        :        "feicui ring",
                        "滄悕賭硌"        :        "feixue ring",
                        "豜罣賭硌"        :        "zizhu ring",
                        "忤嘎賭硌"        :        "shougu ring",
                ]),
        "hands"                :        
                ([
                        "霜堁忒杶"        :        "liuyun glove",
                        "喪褻忒杶"        :        "chilian glove",
                        "剞拸忒杶"        :        "xuwu glove",
                        "攃踢忒杶"        :        "liujin glove",
                        "旛沺忒杶"        :        "bingtie glove",
                ]),
        "boots"                :        
                ([
                        "霜堁悒"        :        "liuyun shoes",
                        "喪褻悒"        :        "chilian shoes",
                        "剞拸悒"        :        "xuwu shoes",
                        "攃踢悒"        :        "liujin shoes",
                        "鳶韓悒"        :        "huolong shoes",
                        "忤悒"        :        "shoupi shoes",
                        "肣挴悒"        :        "tongya shoes",
                        "儕沺悒"        :        "jingtie shoes",
                        "傚瑞悒"        :        "chengfeng shoes",
                        "誥恇悒"        :        "huwen shoes",
                        "檢悒"        :        "polang shoes",
                ]),
]);
