//昜
mapping weapon_file =
([
        "sword"  : "/clone/weapon/gangjian",   //詩膛
        "blade"  : "/clone/weapon/gangdao",    //詩絮
        "hammer" : "/clone/weapon/falun",      //楊謫
        "staff"  : "/clone/weapon/gangzhang",  //詩桱
        "whip"   : "/clone/weapon/changbian",  //酗晝
]);

//伎粗
string *all_color =
({
        "$WHT$", "$YEL$", "$MAG$", "$CYN$", "$BLU$", "$GRN$", "$RED$",
        "$HIW$", "$HIY$", "$HIM$", "$HIC$", "$HIB$", "$HIG$", "$HIR$",
});

//笢袟
mapping name_a =
([
        /*
        "渣踐" : "cuojin",
        "趙嘎" : "huagu",
        "呯陑" : "suixin",
        "囷儕" : "sunjing",
        "柲悛" : "xixue",
        */
        "蚅僸" : "youming",
        "濘霪" : "leiming",
        "蠡攪" : "niepan",
        "豜栠" : "ziyang",
        "喪秝" : "chiyin",
        "蹊毞" : "lietian",
        "扜骯" : "shehun",
        "藻蹕" : "moluo",
        "鳶栠" : "huoyang",
        "褉毞" : "bintian",
        "氅毞" : "juntian",
        "韓朒" : "longyan",
        "喪牳" : "chixia",
        "箇" : "qinghong",
        "著蜮" : "dique",
        "嘉堎" : "guyue",
        "睦藹" : "fumo",
        "燭鳶" : "lihuo",
        "党蹕" : "xiuluo",
        "陎堎" : "xingyue",
        "袚骯" : "zhuihun",
        "髦毞" : "huntian",
        "髦啋" : "hunyuan",
        "袚骯" : "zhuihun",
        "嗤韜" : "duoming",
//////////////////////////////
        "囮朸" : "shishen",
        "喋" : "zhiri",
        "葑朸" : "shishen",
        "蟒陎" : "lianxing",
        "拸朸" : "wushen",
        "肂堎" : "yaoyue",
        "岕藹" : "shimo",
        "堎牳" : "yuexia",
        "壺藹" : "chumo",
        "朸瑞" : "shenfeng",
        "諾橈" : "kongjue",
        "堎賞" : "yuejie",
        "瑞俴" : "fengxing",
        "錘瑞" : "lingfeng",
        "滄豪" : "feihua",
        "紨堎" : "zhuyue",
        "陎" : "piaoxing",
        "嚃陎" : "xuanxing",
        "評敃" : "diewu",
        "諾敷" : "kongji",
        "堎" : "piaoyue",
        "鍾瑞" : "lingfeng",
        "襞朸" : "mengshen",
        "剿" : "duanqing",
        "袚陎" : "zhuixing",
        "鍾雌" : "linghui",
        "偭悕" : "aoxue",
        "窉韓" : "yinlong",
        "紹堎" : "canyue",
        "隅瑞" : "dingfeng",
        "瘋嫖" : "haoguang",
        "砱" : "qingyi",
        "瑭嫖" : "haoguang",
        "鍾陎" : "lingxing",
        "陎" : "qixing",
        "剿堎" : "duanyue",
        "袚堁" : "zhuiyun",
        "瑰" : "haoqing",
        "膛陑" : "jianxin",
        "錘堁" : "lingyun",
        "韓倛" : "longxing",
        "剿闕" : "duanmai",
        "橈" : "jueqing",
        "諾" : "pokong",
        "梮藹" : "zhanmo",
        "壑" : "qiankun",
        "箄陎" : "hongxing",
        "剿諾" : "duankong",
        "謨荌" : "lueying",
        "酵荌" : "huanying",
        "擰陎" : "lanxing",
        "幗韓" : "gunlong",
        "悕" : "piaoxue",
        "葡迾" : "fuyu",
        "楹堁" : "fanyun",
        "蔥藹" : "xiangmo",
        "漁" : "qiuhan",
        "萇嫖" : "dianguang",
        "瑞濘" : "fenglei",
        "敖" : "biri",
        "酵藹" : "huanmo",
        "剞琱" : "xumi",
        "蚅隴" : "youming",
        "僸朸" : "mingshen",
        "朒郜" : "yanyu",
        "栭陑" : "yanxin",
        "瑞荌" : "fengying",
        "棼堎" : "yanyue",
        "栜俴" : "yanxing",
        "韓彴" : "longshe",
        "鍾彴" : "lingshe",
        "鏈諾" : "miaokong",
        "縢陎" : "yaoxing",
        "咡諾" : "wangkong",
        "鳥陑" : "chenxin",
        "酵堎" : "huanyue",
        "橈鳥" : "juechen",
        "酗管" : "changhen",
        "喊瑞" : "chifeng",
        "毞俴" : "tianxing",
        "毞賹" : "tiangang",
        "華伢" : "disha",
        "藜韓" : "jiaolong",
        "韓朸" : "longshen",
        "酗諾" : "changkong",
        "岕嗷" : "shigu",
        "瑞" : "fengren",
        "漁嫖" : "hanguang",
        "隅陑" : "dingxin",
        "酵敃" : "huanwu",
        "秬" : "yiri",
        "嘉陽" : "guding",
        "毞哱" : "tianxuan",
        "怮憤" : "taiji",
        "毞瑞" : "tianfeng",
        "拸憤" : "wuji",
////////////////////////////////
        "麥阨" : "chenshui",
        "喪栭" : "chiyan",
        "絕諼" : "dangkou",
        "樄堎" : "huiyue",
        "桽珗" : "zhaoye",
        "袚" : "zhuiri",
        "剿蜮" : "duanque",
        "倢毞" : "xingtian",
        // 儂駉﹜紳珧﹜蚅﹜啃桵﹜寤轄﹜操鍾﹜旮賹﹜嬝
        // 填懂﹜哱緒﹜醫朸﹜攫藄﹜征騿６蛗迭Ｈ藟鶠〣拊
]);

//袟
mapping name_b =
([
        "梨陑" : "bingxin",
        "漁堎" : "hanyue",
        "哱毞" : "xuantian",
        "悕莽" : "xuechan",
        "薛" : "qingli",
        "豜栭" : "ziyan",
        "怮哱" : "taixuan",
        "轄栭" : "lieyan",
        "嫗" : "guanri",
        "堎" : "poyue",
        "韓" : "qinglong",
        "啞誥" : "baihu",
        "紾" : "zhuque",
        "哱挕" : "xuanwu",
        "攫嘉" : "pangu",
]);
