#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "zhao yishang",
                "name":        "趙一傷",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/zhao1.c",
        ]),
        ([
                "id":          "sun sanhui",
                "name":        "孫三毀",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/sun3.c",
        ]),
        ([
                "id":          "li sicui",
                "name":        "李四摧",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/li4.c",
        ]),
        ([
                "id":          "zhang san",
                "name":        "張三",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/wudang/npc/baibian.c",
        ]),
        ([
                "id":          "jiang baisheng",
                "name":        "江百勝",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taishan/npc/jiang.c",
        ]),
        ([
                "id":          "yafu",
                "name":        "啞婦",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hengshan/npc/yafu.c",
        ]),
        ([
                "id":          "little monkey",
                "name":        "小猴",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/little_monkey.c",
        ]),
        ([
                "id":          "ha dani",
                "name":        "哈達尼",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guanwai/npc/hadani.c",
        ]),
        ([
                "id":          "dongbei hu",
                "name":        "東北虎",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guanwai/npc/dongbeihu.c",
        ]),
        ([
                "id":          "diao",
                "name":        "[1;33m金雕[2;37;0m",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guanwai/npc/diao.c",
        ]),
        ([
                "id":          "hei xiong",
                "name":        "[36m黑熊[2;37;0m",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guanwai/npc/bear.c",
        ]),
        ([
                "id":          "huanan hu",
                "name":        "華南虎",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/yanping/npc/huananhu.c",
        ]),
        ([
                "id":          "wu liupo",
                "name":        "吳六破",
                "type":        "殺",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/wu6.c",
        ]),
        ([
                "id":          "heiyi ren",
                "name":        "黑衣人",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/heimuya/npc/heiyiren.c",
        ]),
        ([
                "id":          "young girl",
                "name":        "年輕女弟子",
                "type":        "殺",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/shenlong/npc/girl.c",
        ]),
        ([
                "id":          "yu renyan",
                "name":        "余人彥",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/qingcheng/npc/yuyan.c",
        ]),
        ([
                "id":          "jia renda",
                "name":        "賈人達",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/qingcheng/npc/jia.c",
        ]),
        ([
                "id":          "wu liupo",
                "name":        "吳六破",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/wu6.c",
        ]),
        ([
                "id":          "laohu",
                "name":        "老虎",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/wudang/npc/laohu.c",
        ]),
        ([
                "id":          "zhen youqing",
                "name":        "甄有慶",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/suzhou/npc/shiye.c",
        ]),
        ([
                "id":          "zhang laosan",
                "name":        "章老三",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/shenlong/npc/zhang3.c",
        ]),
        ([
                "id":          "mu jianping",
                "name":        "沐劍屏",
                "type":        "殺",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/shenlong/npc/mujianping.c",
        ]),
        ([
                "id":          "horse",
                "name":        "[1;36m青驄馬[2;37;0m",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/obj/horse.c",
        ]),
        ([
                "id":          "wanyan honglie",
                "name":        "完顏洪烈",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guiyun/npc/wanyanhonglie.c",
        ]),
        ([
                "id":          "qiu qianzhang",
                "name":        "裘千丈",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/qiuqianzhang.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "青衣武士",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi3.c",
        ]),
        ([
                "id":          "shen renjun",
                "name":        "申人俊",
                "type":        "殺",
                "bonus":       96,
                "msg":        "",
                "object":      "/d/qingcheng/npc/shen.c",
        ]),
        ([
                "id":          "yan ji",
                "name":        "閻基",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guanwai/npc/yanji.c",
        ]),
        ([
                "id":          "wolf",
                "name":        "[37m野狼[2;37;0m",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/clone/quarry/lang2.c",
        ]),
        ([
                "id":          "feng yiming",
                "name":        "鳳一鳴",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/foshan/npc/fengyiming.c",
        ]),
        ([
                "id":          "cow",
                "name":        "[1;37m大黃牛[2;37;0m",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/wudang/npc/cow.c",
        ]),
        ([
                "id":          "qian erbai",
                "name":        "錢二敗",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/qian2.c",
        ]),
        ([
                "id":          "sun baopi",
                "name":        "孫剝皮",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/suzhou/npc/sun.c",
        ]),
        ([
                "id":          "gongzi",
                "name":        "公子哥",
                "type":        "殺",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/suzhou/npc/gongzi.c",
        ]),
        ([
                "id":          "feng zhengdong",
                "name":        "馮正東",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/suzhou/npc/feng.c",
        ]),
        ([
                "id":          "fang yi",
                "name":        "方怡",
                "type":        "殺",
                "bonus":       62,
                "msg":        "",
                "object":      "/d/shenlong/npc/fangyi.c",
        ]),
        ([
                "id":          "young boy",
                "name":        "年輕弟子",
                "type":        "殺",
                "bonus":       58,
                "msg":        "",
                "object":      "/d/shenlong/npc/boy4.c",
        ]),
        ([
                "id":          "old man",
                "name":        "老者",
                "type":        "殺",
                "bonus":       81,
                "msg":        "",
                "object":      "/d/shenlong/npc/old.c",
        ]),
        ([
                "id":          "fang renzhi",
                "name":        "方人智",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/qingcheng/npc/fang.c",
        ]),
        ([
                "id":          "zheng qimie",
                "name":        "鄭七滅",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/zheng7.c",
        ]),
        ([
                "id":          "wang bashuai",
                "name":        "王八衰",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/wang8.c",
        ]),
        ([
                "id":          "laohu",
                "name":        "老虎",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/hangzhou/npc/laohu.c",
        ]),
        ([
                "id":          "zhong wanchou",
                "name":        "鐘萬仇",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/zhong.c",
        ]),
        ([
                "id":          "zhou wushu",
                "name":        "周五輸",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/zhou5.c",
        ]),
        ([
                "id":          "yang lianting",
                "name":        "楊蓮亭",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/heimuya/npc/yang.c",
        ]),
        ([
                "id":          "guo fu",
                "name":        "郭芙",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/guofu.c",
        ]),
        ([
                "id":          "gan baobao",
                "name":        "甘寶寶",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/gan.c",
        ]),
        ([
                "id":          "wan daping",
                "name":        "萬大平",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/songshan/npc/wan.c",
        ]),
        ([
                "id":          "qian erbai",
                "name":        "錢二敗",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/qian2.c",
        ]),
        ([
                "id":          "ma zei",
                "name":        "馬賊",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huanghe/npc/mazei.c",
        ]),
        ([
                "id":          "ouyang ke",
                "name":        "歐陽克",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/ouyang/ouyangke.c",
        ]),
        ([
                "id":          "caihua zi",
                "name":        "採花子",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xingxiu/npc/caihua.c",
        ]),
        ([
                "id":          "shi dengda",
                "name":        "史登達",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/songshan/npc/shi.c",
        ]),
        ([
                "id":          "young boy",
                "name":        "年輕弟子",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/shenlong/npc/boy3.c",
        ]),
        ([
                "id":          "young boy",
                "name":        "年輕弟子",
                "type":        "殺",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/shenlong/npc/boy.c",
        ]),
        ([
                "id":          "ji rentong",
                "name":        "吉人通",
                "type":        "殺",
                "bonus":       96,
                "msg":        "",
                "object":      "/d/qingcheng/npc/ji.c",
        ]),
        ([
                "id":          "shan yang",
                "name":        "山羊",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/shanyang.c",
        ]),
        ([
                "id":          "laohu",
                "name":        "老虎",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/laohu.c",
        ]),
        ([
                "id":          "jianghu yiren",
                "name":        "江湖藝人",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/jianghuyiren.c",
        ]),
        ([
                "id":          "he hongyao",
                "name":        "何紅藥",
                "type":        "殺",
                "bonus":       96,
                "msg":        "",
                "object":      "/d/dali/npc/hehongyao.c",
        ]),
        ([
                "id":          "gongzi",
                "name":        "貴公子",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/dali/npc/guigongzi.c",
        ]),
        ([
                "id":          "shui niu",
                "name":        "水牛",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/cow.c",
        ]),
        ([
                "id":          "wu tiande",
                "name":        "吳天德",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/wutiande.c",
        ]),
        ([
                "id":          "tang huai",
                "name":        "唐槐",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/tanghuai.c",
        ]),
        ([
                "id":          "tang",
                "name":        "唐掌櫃",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/tanghua.c",
        ]),
        ([
                "id":          "tan youji",
                "name":        "譚友紀",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/shiye.c",
        ]),
        ([
                "id":          "shi song",
                "name":        "史鬆",
                "type":        "殺",
                "bonus":       76,
                "msg":        "",
                "object":      "/d/city/npc/shisong.c",
        ]),
        ([
                "id":          "cui yuanwai",
                "name":        "崔員外",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/city/npc/cui.c",
        ]),
        ([
                "id":          "cheng yaofa",
                "name":        "程藥發",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/cheng.c",
        ]),
        ([
                "id":          "zhang san",
                "name":        "張三",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/city/npc/baibian.c",
        ]),
        ([
                "id":          "liang xinglu",
                "name":        "樑興祿",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/zhifu.c",
        ]),
        ([
                "id":          "li boyuan",
                "name":        "李博淵",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/xueshi.c",
        ]),
        ([
                "id":          "tie gongji",
                "name":        "鐵公雞",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/tiegongji.c",
        ]),
        ([
                "id":          "tang",
                "name":        "趟子手",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/tang.c",
        ]),
        ([
                "id":          "shu chi",
                "name":        "書痴",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/shuchi.c",
        ]),
        ([
                "id":          "chen jisheng",
                "name":        "陳繼盛",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/shiye.c",
        ]),
        ([
                "id":          "ling feixue",
                "name":        "凌飛雪",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/changan/npc/lingfeixue.c",
        ]),
        ([
                "id":          "qian laoben",
                "name":        "錢老本",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/qianlaoben.c",
        ]),
        ([
                "id":          "lama",
                "name":        "喇嘛",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/lama.c",
        ]),
        ([
                "id":          "feng jizhong",
                "name":        "風際中",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/fengjizhong.c",
        ]),
        ([
                "id":          "qing",
                "name":        "小青",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/baituo/npc/xiaoqing.c",
        ]),
        ([
                "id":          "trainer",
                "name":        "教練",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/trainer.c",
        ]),
        ([
                "id":          "tiger",
                "name":        "老虎",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/tiger.c",
        ]),
        ([
                "id":          "snaker",
                "name":        "舞蛇人",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/snaker.c",
        ]),
        ([
                "id":          "shanzei tou",
                "name":        "山賊頭",
                "type":        "殺",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei3.c",
        ]),
        ([
                "id":          "playboy",
                "name":        "花花公子",
                "type":        "殺",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/baituo/npc/playboy.c",
        ]),
        ([
                "id":          "men wei",
                "name":        "門衛",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/baituo/npc/menwei.c",
        ]),
        ([
                "id":          "lion",
                "name":        "雄獅",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/baituo/npc/lion.c",
        ]),
        ([
                "id":          "ge lunbu",
                "name":        "葛倫布",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/gelunbu.c",
        ]),
        ([
                "id":          "mo bushou",
                "name":        "莫不收",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/mo-bu.c",
        ]),
});
mapping query_questsn()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
